export { AlunoKPIs } from "./AlunoKPIs";
export { AlunoTable } from "./AlunoTable";
export { AlunoViewDialog } from "./AlunoViewDialog";
export { AlunoEnturmarDialog } from "./AlunoEnturmarDialog";
export { AlunoBatchActions, ExportButton } from "./AlunoBatchActions";
export { AlunoFotoUpload } from "./AlunoFotoUpload";
export { AlunoDocumentos } from "./AlunoDocumentos";
export { AlunoHabilidades } from "./AlunoHabilidades";
export { AlunoTimeline } from "./AlunoTimeline";
export type { Aluno, Responsavel, Curso, Turma, StatusFilter } from "./types";
export { STATUS_CONFIG } from "./types";
